import type { Source } from "@/types";

export const sources: Source[] = [
  {
    nome: "ge",
    url: "https://ge.globo.com",
    tipo: "rss",
    rss: "https://globoesporte.globo.com/rss/ge/",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "ESPN Brasil",
    url: "https://www.espn.com.br/futebol/selecao-brasileira",
    tipo: "site",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "UOL Esporte",
    url: "https://www.uol.com.br/esporte/",
    tipo: "rss",
    rss: "https://rss.uol.com.br/feed/esporte.xml",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "Placar",
    url: "https://placar.com.br",
    tipo: "rss",
    rss: "https://placar.com.br/rss.xml",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "Band Esportes",
    url: "https://www.band.com.br/esportes",
    tipo: "rss",
    rss: "https://rss.bs.vibra.digital/feed.xml?site=esportes",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "CNN Brasil",
    url: "https://www.cnnbrasil.com.br/esportes/futebol/selecao-brasileira/",
    tipo: "site",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "Lance!",
    url: "https://www.lance.com.br",
    tipo: "site",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "TNT Sports",
    url: "https://tntsports.com.br",
    tipo: "site",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "CBF",
    url: "https://www.cbf.com.br/selecao-brasileira",
    tipo: "site",
    idioma: "pt-BR",
    ativo: true,
  },
  {
    nome: "FIFA",
    url: "https://www.fifa.com",
    tipo: "site",
    idioma: "en",
    ativo: true,
  },
];
